version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      # Add more volumes if needed, e.g., for static files
      # - static_volume:/app/static
    ports:
      - "8000:8000"
