"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

from langfuse import Langfuse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wca@2o7lu59wvile-s2bofm4^=%^#70qcb=^qmfxlqbx&15oxi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg', 
    'rest_framework', 
    'rest_framework_simplejwt.token_blacklist', 
    'django_prometheus',
    'django_extensions',
    'user_manager', 
    'kakao_manager', 
    'naver_manager', 
    'ai_manager',
    'community', 
    'crew',
    'retrospect',
    'payment',
    "django_celery_beat",
    "django_celery_results"
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.otel.RequestLoggingMiddleware', 
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_MYSQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_MYSQL_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_MYSQL_USER', ''),
        'PASSWORD': os.getenv('DB_MYSQL_PASSWORD', ''),
        'HOST': os.getenv('DB_MYSQL_HOST', 'localhost'),
        'PORT': os.getenv('DB_MYSQL_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "user_manager.User"

SIMPLE_JWT = {
    'TOKEN_OBTAIN_SERIALIZER': 'token_manager.serializer.CustomTokenObtainPairSerializer',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Swagger

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "JWT Token"
        }
    },
    'SECURITY_REQUIREMENTS': [{
        'BearerAuth': []
    }]
}

langfuse = Langfuse(
    host=os.getenv("LANGFUSE_HOST"),
    secret_key=os.getenv("LANGFUSE_SECRET_KEY"),
    public_key=os.getenv("LANGFUSE_PUBLIC_KEY"),
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Load API keys and URIs from environment variables
KAKAO_REST_API_KEY = os.getenv('KAKAO_REST_API_KEY', '')
KAKAO_REDIRECT_URI = os.getenv('KAKAO_REDIRECT_URI', '')

NAVER_REST_API_KEY = os.getenv('NAVER_REST_API_KEY', '')
NAVER_SECRET_API_KEY = os.getenv('NAVER_SECRET_API_KEY', '')
NAVER_REDIRECT_URI = os.getenv('NAVER_REDIRECT_URI', '')

KAKAO_PAY_CLIENT_ID = os.getenv('KAKAO_PAY_CLIENT_ID', '')
KAKAO_PAY_SECRET = os.getenv('KAKAO_PAY_SECRET', '')
KAKAO_PAY_KEY = os.getenv('KAKAO_PAY_KEY', '')
CID = os.getenv('CID', '')

REDIS_HOST = os.getenv('REDIS_HOST', 'redis') # 기본 호스트명을 'redis' (Docker Compose용) 또는 'localhost' 등으로 설정
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PORT_SYSTEM = os.getenv('REDIS_PORT_SYSTEM') # Celery 브로커에는 직접 사용되지 않을 수 있음
REDIS_PW = os.getenv('REDIS_PW')

# Celery
# CELERY_BROKER_URL 환경 변수가 있으면 그 값을 사용하고,
# 없으면 REDIS_HOST, REDIS_PORT, REDIS_PW를 조합하여 생성
_celery_broker_db = '0' # Celery 브로커용 Redis DB 번호

if REDIS_PW:
    _constructed_broker_url = f"redis://:{REDIS_PW}@{REDIS_HOST}:{REDIS_PORT}/{_celery_broker_db}"
else:
    _constructed_broker_url = f"redis://{REDIS_HOST}:{REDIS_PORT}/{_celery_broker_db}"

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _constructed_broker_url)
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

