# Generated by Django 5.2 on 2025-04-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_list', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Retrospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('kpi_result', models.FloatField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('CREW', 'Crew Only'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('CREW', 'Crew')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectWeeklyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField()),
                ('weekly_kpi', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('CREW', 'Crew')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('CREW', 'Crew'), ('COMMON', 'Common')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('steps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACHIEVED', 'Achieved'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('kpi_description', models.TextField(blank=True)),
                ('kpi_metrics', models.JSONField(blank=True, null=True)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('CREW', 'Crew')], max_length=10)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='LIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='crew.crew')),
            ],
        ),
    ]
