# Generated by Django 5.2 on 2025-04-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="kpi_description",
        ),
        migrations.AddField(
            model_name="challenge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="challenges",
                to="retrospect.plan",
            ),
        ),
    ]
