# Generated by Django 5.2 on 2025-04-16 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0002_initial'),
        ('retrospect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='retrospect.plan'),
        ),
        migrations.AddField(
            model_name='retrospect',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospects', to='retrospect.challenge'),
        ),
        migrations.AddField(
            model_name='retrospect',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrospects', to='crew.crew'),
        ),
        migrations.AddField(
            model_name='retrospect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrospectweeklyanalysis',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analyses', to='crew.crew'),
        ),
        migrations.AddField(
            model_name='retrospectweeklyanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='crew.crew'),
        ),
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrospect',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrospects', to='retrospect.template'),
        ),
        migrations.AddField(
            model_name='userchallengestatus',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='retrospect.challenge'),
        ),
        migrations.AddField(
            model_name='userchallengestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userchallengestatus',
            index=models.Index(fields=['user', 'challenge'], name='retrospect__user_id_69e6a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengestatus',
            unique_together={('user', 'challenge')},
        ),
    ]
