# Generated by Django 5.2 on 2025-04-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0002_remove_challenge_kpi_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="plan",
        ),
        migrations.AddField(
            model_name="retrospect",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retrospects",
                to="retrospect.plan",
            ),
        ),
    ]
