# Generated by Django 5.2 on 2025-04-27 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0003_remove_challenge_plan_retrospect_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='kpi_metrics',
        ),
        migrations.RemoveField(
            model_name='retrospect',
            name='kpi_result',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, default='')),
                ('measurement_unit', models.CharField(blank=True, default='', max_length=50)),
                ('data_type', models.CharField(choices=[('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean')], max_length=10)),
                ('measurement_method', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='retrospect.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KpiDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('value_type', models.CharField(choices=[('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean')], max_length=10)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='retrospect.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_data_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['challenge', 'user'], name='retrospect__challen_7288b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('challenge', 'user', 'name')},
        ),
        migrations.AddIndex(
            model_name='kpidataentry',
            index=models.Index(fields=['kpi', 'user', 'record_date'], name='retrospect__kpi_id_a8ebbb_idx'),
        ),
    ]
