# Generated by Django 5.2 on 2025-04-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0006_plan_created_at_plan_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KpiResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="retrospect.challenge",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="retrospect.kpi",
                    ),
                ),
                (
                    "retrospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="retrospect.retrospect",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Result",
                "verbose_name_plural": "KPI Results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "challenge", "kpi", "retrospect"],
                        name="retrospect__user_id_de0192_idx",
                    )
                ],
                "unique_together": {("user", "challenge", "kpi", "retrospect")},
            },
        ),
        migrations.CreateModel(
            name="KpiWeeklyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("total_score", models.FloatField(blank=True, null=True)),
                ("retrospect_count", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_weekly_results",
                        to="retrospect.challenge",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_weekly_results",
                        to="retrospect.kpi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_weekly_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "challenge", "kpi", "week_start_date"],
                        name="retrospect__user_id_aaaa39_idx",
                    )
                ],
                "unique_together": {("user", "challenge", "kpi", "week_start_date")},
            },
        ),
    ]
