# Generated by Django 5.2 on 2025-05-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0006_plan_created_at_plan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='hashtag',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospect',
            name='content',
            field=models.JSONField(),
        ),
    ]
