# Generated by Django 5.2 on 2025-05-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0007_kpiresult_kpiweeklyresult"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KpiWeeklyResult",
        ),
    ]
