# Generated by Django 5.2 on 2025-05-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0008_delete_kpiweeklyresult"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KpiDataEntry",
        ),
    ]
