# Generated by Django 5.2 on 2025-05-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0007_template_description_template_hashtag_and_more'),
        ('retrospect', '0008_delete_kpiweeklyresult'),
    ]

    operations = [
    ]
