# Generated by Django 5.2 on 2025-05-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retrospect", "0009_delete_kpidataentry"),
        ("retrospect", "0009_merge_20250505_1518"),
    ]

    operations = []
