# Generated by Django 5.2 on 2025-05-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        ('retrospect', '0009_merge_20250505_1518'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    # 1. 먼저 필드들을 추가
    migrations.AddField(
        model_name='retrospectweeklyanalysis',
        name='challenge',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analyses', to='retrospect.challenge'),
    ),
    migrations.AddField(
        model_name='retrospectweeklyanalysis',
        name='avg_score',
        field=models.FloatField(default=0.0),
    ),
    migrations.AddField(
        model_name='retrospectweeklyanalysis',
        name='comment',
        field=models.TextField(default=''),
    ),
    migrations.AddField(
        model_name='retrospectweeklyanalysis',
        name='max_score',
        field=models.FloatField(default=0.0),
    ),
    migrations.AddField(
        model_name='retrospectweeklyanalysis',
        name='min_score',
        field=models.FloatField(default=0.0),
    ),
    migrations.AlterField(
        model_name='retrospectweeklyanalysis',
        name='summary',
        field=models.TextField(default=''),
    ),
    
    # 2. 그 다음 unique_together 설정
    migrations.AlterUniqueTogether(
        name='retrospectweeklyanalysis',
        unique_together={('challenge', 'owner_type', 'user', 'start_date', 'end_date')},
    ),
    
    # 3. 마지막으로 인덱스 추가
    migrations.AddIndex(
        model_name='retrospectweeklyanalysis',
        index=models.Index(fields=['challenge', 'owner_type', 'user', 'start_date'], name='retrospect__challen_93c581_idx'),
    ),
    migrations.AddIndex(
        model_name='retrospectweeklyanalysis',
        index=models.Index(fields=['challenge', 'owner_type', 'crew', 'start_date'], name='retrospect__challen_85e05e_idx'),
    ),
    
    # 4. 기존 필드 제거
    migrations.RemoveField(
        model_name='retrospectweeklyanalysis',
        name='weekly_kpi',
    ),
]
