# Generated by Django 5.2 on 2025-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0010_alter_retrospectweeklyanalysis_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiresult',
            name='llm_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='LLM 회고 피드백'),
        ),
    ]
