# Generated by Django 5.2 on 2025-05-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0010_alter_retrospectweeklyanalysis_unique_together_and_more'),
        ('retrospect', '0010_merge_20250512_0159'),
    ]

    operations = [
    ]
