# Generated by Django 5.2.1 on 2025-05-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0011_kpiresult_llm_feedback'),
        ('retrospect', '0011_merge_20250515_0124'),
    ]

    operations = [
    ]
