# Generated by Django 5.2.1 on 2025-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospect', '0012_merge_20250516_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiresult',
            name='llm_feedback',
        ),
        migrations.AddField(
            model_name='retrospectweeklyanalysis',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectweeklyanalysis',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectweeklyanalysis',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectweeklyanalysis',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectweeklyanalysis',
            name='min_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectweeklyanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
