# Generated by Django 5.2.1 on 2025-05-19 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(blank=True, max_length=50, null=True)),
                ('tid', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=50)),
                ('sid', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_order_id', models.CharField(max_length=50)),
                ('partner_user_id', models.CharField(max_length=50)),
                ('payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tax_free', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('green_deposit', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ready', '결제 준비'), ('approved', '결제 승인'), ('failed', '결제 실패'), ('canceled', '결제 취소')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
