# Generated by Django 5.2 on 2025-04-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='crew.crew'),
        ),
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
