# Generated by Django 5.2 on 2025-04-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0002_user_profile_image_notification"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
